image: docker:latest

services:
  - docker:dind

variables:
  AWS_DEFAULT_REGION: "us-east-1"  
  ECR_REPOSITORY_URI: "927434171806.dkr.ecr.us-east-1.amazonaws.com/api.comment"

stages:
  - build
  - deploy

before_script:
  - apk add --no-cache python3 py3-pip
  - pip3 install --upgrade awscli
  - aws --version
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set default.region $AWS_DEFAULT_REGION

build_image:
  stage: build
  script:
    - docker build -t api_comment .
    - echo $AWS_SECRET_ACCESS_KEY | docker login -u $AWS_ACCESS_KEY_ID --password-stdin $ECR_REPOSITORY_URI
    - docker tag api_comment:latest $ECR_REPOSITORY_URI
    - docker push $ECR_REPOSITORY_URI

deploy_to_ecs:
  stage: deploy
  script:
    - apk add --no-cache terraform
    - terraform init terraform
    - terraform apply -auto-approve terraform
  only:
    - main
