name: Build and Deploy Docker Image


on:
  push:
    branches:
      - main  
env:
  AWS_REGION: us-east-1
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: ${{ env.AWS_REGION }}

    - name: Build Docker image
      run: |
        docker build -t myapp app
        docker tag myapp:latest ${{ secrets.ECR_REPOSITORY }}:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.ECR_REPOSITORY }}:latest

    - name: Create Task Definition
      run: |
        aws ecs register-task-definition \
          --task-definition ${{ secrets.ECS_TASK_DEFINITION }}

    - name: Update ECS service
      run: |
        aws ecs update-service \
          --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
          --service ${{ secrets.ECS_SERVICE_NAME }} \
          --force-new-deployment \
          
