name: Build and Deploy Docker Image Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0 # Ajuste conforme necessário

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Plan
      run: terraform plan
      working-directory: terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform

    - name: Check Terraform Apply result and Destroy if failed
      if: failure()
      run: |
        echo "Terraform Apply failed, destroying infrastructure..."
        terraform destroy -auto-approve

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: ${{ secrets.AWS_REGION }}

    - name: Build Docker image
      run: |
        docker build -t myapp app
        docker tag myapp:latest ${{ secrets.ECR_REPOSITORY }}:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.ECR_REPOSITORY }}:latest
